# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build the project
cmd = "go build -o ./tmp/main ./cmd/main.go"
# Binary file to run
bin = "tmp/main"
# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp"]
# Log level (debug, info, warn, error, fatal, panic)
log = "debug"

[log]
# Display full timestamp
time = true
# Output the logs to stdout
output = "stdout"
