# dev 
FROM golang:1.24-alpine

RUN apk update && apk add --no-cache git curl
RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY src/go.mod src/go.sum ./
RUN go mod download

COPY src .
EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
